export const VUEX_CONTACT_SEND_EMAIL_REQUEST  = 'VUEX_CONTACT_SEND_EMAIL_REQUEST'
export const VUEX_CONTACT_SEND_EMAIL_SUCCESS  = 'VUEX_CONTACT_SEND_EMAIL_SUCCESS'
export const VUEX_CONTACT_SEND_EMAIL_FAILURE  = 'VUEX_CONTACT_SEND_EMAIL_FAILURE'
export const VUEX_CONTACT_SEND_EMAIL_RESET    = 'VUEX_CONTACT_SEND_EMAIL_RESET'