export const VUEX_UPLOAD_REQUEST              = 'VUEX_UPLOAD_REQUEST'
export const VUEX_UPLOAD_REQUEST_SUCCESS      = 'VUEX_UPLOAD_REQUEST_SUCCESS'
export const VUEX_UPLOAD_REQUEST_FAILURE      = 'VUEX_UPLOAD_REQUEST_FAILURE'

export const VUEX_UPLOAD_ABORT                = 'VUEX_UPLOAD_ABORT'

export const VUEX_UPLOAD_SET_FILE_TO_UPLOAD   = 'VUEX_UPLOAD_SET_FILE_TO_UPLOAD'