export const VUEX_UPLOAD_S3_REQUEST                  = 'VUEX_UPLOAD_S3_REQUEST'
export const VUEX_UPLOAD_S3_REQUEST_SUCCESS          = 'VUEX_UPLOAD_S3_REQUEST_SUCCESS'
export const VUEX_UPLOAD_S3_REQUEST_FAILURE          = 'VUEX_UPLOAD_S3_REQUEST_FAILURE'
export const VUEX_UPLOAD_S3_ABORT                    = 'VUEX_UPLOAD_S3_ABORT'

export const VUEX_UPLOAD_ATTACHMENT_REQUEST          = 'VUEX_UPLOAD_ATTACHMENT_REQUEST'
export const VUEX_UPLOAD_ATTACHMENT_REQUEST_SUCCESS  = 'VUEX_UPLOAD_ATTACHMENT_REQUEST_SUCCESS'
export const VUEX_UPLOAD_ATTACHMENT_REQUEST_FAILURE  = 'VUEX_UPLOAD_ATTACHMENT_REQUEST_FAILURE'

export const VUEX_UPLOAD_SET_FILE_TO_UPLOAD          = 'VUEX_UPLOAD_SET_FILE_TO_UPLOAD'