export const VUEX_ROLE_FETCH_REQUEST = 'VUEX_ROLE_FETCH_REQUEST'
export const VUEX_ROLE_FETCH_SUCCESS = 'VUEX_ROLE_FETCH_SUCCESS'
export const VUEX_ROLE_FETCH_FAILURE = 'VUEX_ROLE_FETCH_FAILURE'

export const VUEX_ROLE_CREATE = 'VUEX_ROLE_CREATE'
export const VUEX_ROLE_CREATE_SUCCESS = 'VUEX_ROLE_CREATE_SUCCESS'
export const VUEX_ROLE_CREATE_FAILURE = 'VUEX_ROLE_CREATE_FAILURE'

export const VUEX_ROLE_TEARDOWN = 'VUEX_ROLE_TEARDOWN'