export const VUEX_UI_HEADER_SHOW = 'VUEX_UI_HEADER_SHOW'
export const VUEX_UI_HEADER_HIDE = 'VUEX_UI_HEADER_HIDE'

export const VUEX_UI_NAVIGATION_SHOW = 'VUEX_UI_NAVIGATION_SHOW'
export const VUEX_UI_NAVIGATION_HIDE = 'VUEX_UI_NAVIGATION_HIDE'
export const VUEX_UI_NAVIGATION_TOGGLE_OPENSTATE = 'VUEX_UI_NAVIGATION_TOGGLE_OPENSTATE'
export const VUEX_UI_NAVIGATION_SET_TITLE = 'VUEX_UI_NAVIGATION_SET_TITLE'
export const VUEX_UI_NAVIGATION_ENABLED = 'VUEX_UI_NAVIGATION_ENABLED'
export const VUEX_UI_NAVIGATION_DISABLED = 'VUEX_UI_NAVIGATION_DISABLED'

export const VUEX_UI_OVERLAY_CONTAINER_SHOW = 'VUEX_UI_OVERLAY_CONTAINER_SHOW'
export const VUEX_UI_OVERLAY_CONTAINER_HIDE = 'VUEX_UI_OVERLAY_CONTAINER_HIDE'
export const VUEX_UI_OVERLAY_CONTAINER_SET_STATE = 'VUEX_UI_OVERLAY_CONTAINER_SET_STATE'
export const VUEX_UI_OVERLAY_CONTAINER_SET_COMPONENT = 'VUEX_UI_OVERLAY_CONTAINER_SET_COMPONENT'

export const VUEX_UI_DIALOG_CONTAINER_SHOW = 'VUEX_UI_DIALOG_CONTAINER_SHOW'
export const VUEX_UI_DIALOG_CONTAINER_HIDE = 'VUEX_UI_DIALOG_CONTAINER_HIDE'
export const VUEX_UI_DIALOG_CONTAINER_SET_STATE = 'VUEX_UI_DIALOG_CONTAINER_SET_STATE'
export const VUEX_UI_DIALOG_CONTAINER_SET_COMPONENT = 'VUEX_UI_DIALOG_CONTAINER_SET_COMPONENT'

export const VUEX_UI_LOGIN_CONTAINER_SHOW = 'VUEX_UI_LOGIN_CONTAINER_SHOW'
export const VUEX_UI_LOGIN_CONTAINER_HIDE = 'VUEX_UI_LOGIN_CONTAINER_HIDE'
export const VUEX_UI_LOGIN_CONTAINER_SET_STATE = 'VUEX_UI_LOGIN_CONTAINER_SET_STATE'

export const VUEX_UI_NOTIFICATIONS_CONTAINER_SHOW = 'VUEX_UI_NOTIFICATIONS_CONTAINER_SHOW'
export const VUEX_UI_NOTIFICATIONS_CONTAINER_HIDE = 'VUEX_UI_NOTIFICATIONS_CONTAINER_HIDE'
export const VUEX_UI_NOTIFICATIONS_CONTAINER_SET_STATE = 'VUEX_UI_NOTIFICATIONS_CONTAINER_SET_STATE'
export const VUEX_UI_NOTIFICATIONS_CONTAINER_SET_COMPONENT = 'VUEX_UI_NOTIFICATIONS_CONTAINER_SET_COMPONENT'
export const VUEX_UI_NOTIFICATIONS_CONTAINER_DEFAULT_DELAY = 5000

export const VUEX_UI_HEADER_LOGO = require('@/assets/app/images/header-logo.svg')
export const VUEX_UI_ABOUT_BIO_PHOTO = require('@/assets/app/images/profile-photo.png')
