export const VUEX_ROUTING_NAVIGATE_TO_ROUTE   = 'VUEX_ROUTING_NAVIGATE_TO_ROUTE'
export const VUEX_ROUTING_PUSH_ROUTE          = 'VUEX_ROUTING_PUSH_ROUTE'
export const VUEX_ROUTING_EXIT_ROUTE_TEARDOWN = 'VUEX_ROUTING_EXIT_ROUTE_TEARDOWN'