export const VUEX_ROUTING_INIT = 'VUEX_ROUTING_INIT'
export const VUEX_ROUTING_NAVIGATE_TO_ROUTE = 'VUEX_ROUTING_NAVIGATE_TO_ROUTE'
export const VUEX_ROUTING_EXIT_ROUTE_TEARDOWN = 'VUEX_ROUTING_EXIT_ROUTE_TEARDOWN'
export const VUEX_ROUTING_PUSH_ROUTE = 'VUEX_ROUTING_PUSH_ROUTE'
export const VUEX_ROUTING_ENTER_ROUTE = 'VUEX_ROUTING_ENTER_ROUTE'
export const VUEX_ROUTING_SET_CURRENT_ROUTE = 'VUEX_ROUTING_SET_CURRENT_ROUTE'
export const VUEX_ROUTING_SET_PREVIOUS_ROUTE = 'VUEX_ROUTING_SET_PREVIOUS_ROUTE'

export const VUEX_ROUTING_ROUTE_TO_HOME = 'VUEX_ROUTING_ROUTE_TO_HOME'

export const VUEX_ROUTING_ENTER_PROJECT = 'VUEX_ROUTING_ENTER_PROJECT'
export const VUEX_ROUTING_ENTER_EXPERIMENT = 'VUEX_ROUTING_ENTER_EXPERIMENT'
export const VUEX_ROUTING_ENTER_ROLES = 'VUEX_ROUTING_ENTER_ROLES'
export const VUEX_ROUTING_ENTER_ROLE = 'VUEX_ROUTING_ENTER_ROLE'

export const VUEX_ROUTING_PREVIOUS_PAGE = 'VUEX_ROUTING_PREVIOUS_PAGE'
