export default {
    HADDIX_ATTACHMENT_MODEL__PROJECT          : 'App_Project',

    HADDIX_ATTACHMENT_USAGE_TYPE__THUMBNAIL   : 'thumbnail',
    HADDIX_ATTACHMENT_USAGE_TYPE__CAROUSEL    : 'carousel',
    HADDIX_ATTACHMENT_USAGE_TYPE__BODY        : 'body',
    HADDIX_ATTACHMENT_USAGE_TYPE__VIDEO       : 'video',

    HADDIX_ATTACHMENTS_S3_QUEUE_SIZE          : 4,

    HADDIX_UPLOAD_S3_UPLOAD_STATUS__PENDING   : 'pending',
    HADDIX_UPLOAD_S3_UPLOAD_STATUS__STARTED   : 'started',
    HADDIX_UPLOAD_S3_UPLOAD_STATUS__SUCCESS   : 'success',
    HADDIX_UPLOAD_S3_UPLOAD_STATUS__FAILURE   : 'failure',

    HADDIX_UPLOAD_ATTACHMENT_STATUS__PENDING : 'pending',
    HADDIX_UPLOAD_ATTACHMENT_STATUS__STARTED : 'started',
    HADDIX_UPLOAD_ATTACHMENT_STATUS__SUCCESS : 'success',
    HADDIX_UPLOAD_ATTACHMENT_STATUS__FAILURE : 'failure'
}