export const VUEX_CONSTANTS_INIT          = 'VUEX_CONTANTS_INIT'
export const VUEX_CONSTANTS_INITIALIZED   = 'VUEX_CONSTANTS_INITIALIZED'
export const VUEX_CONSTANTS_SET_ALL       = 'VUEX_CONSTANTS_SET_ALL'

export const VUEX_PROPERTIES_INIT         = 'VUEX_PROPERTIES_INIT'
export const VUEX_PROPERTIES_INITIALIZED  = 'VUEX_PROPERTIES_INITIALIZED'
export const VUEX_PROPERTIES_SET_ALL      = 'VUEX_PROPERTIES_SET_ALL'