/* eslint-disable no-unused-vars */
export default {
	projectTypes: [
		{ name: 'Collaberation', value: 'collaberation' },
		{ name: 'Experiment', value: 'experiment' },
		{ name: 'Personal', value: 'personal' },
		{ name: 'New Role', value: 'new_role' },
		{ name: 'Work', value: 'work' }
		// { name: '', value: '' },
	],

	projectRoles: [
		{ name: 'Creative Director', value: 'creative_director' },
		{ name: 'Designer', value: 'designer' },
		{ name: 'Developer', value: 'developer' },
		{ name: 'Front-end Engineer', value: 'front_end_engineer' },
		{ name: 'Lead Developer', value: 'lead_developer' },
		{ name: 'Lead Front-end Engineer', value: 'lead_front_end_engineer' },
		{ name: 'Support Engineer', value: 'support_engineer' },
		{ name: 'Technical Consultant', value: 'technical_consultant' }
	],

	projectClients: [
		{ name: 'Amazon', value: 'amazon' },
		{ name: 'Best Buy', value: 'best_buy' },
		{ name: 'Blowfish Shoes', value: 'blowfish_shoes' },
		{ name: 'Chevron', value: 'chevron' },
		{ name: 'City of New York', value: 'new_york' },
		{ name: 'Cirque Du Solel', value: 'cirque_du_solel' },
		{ name: 'DirecTv', value: 'directv' },
		{ name: 'Disney Channel', value: 'disney_channel' },
		{ name: 'ESPN', value: 'espn' },
		{ name: 'FX', value: 'fx' },
		{ name: 'The Gary Group', value: 'gary_group' },
		{ name: 'HBO', value: 'hbo' },
		{ name: 'iTunes', value: 'itunes' },
		{ name: 'MGM Grand', value: 'mgm_grand' },
		{ name: 'Nexon', value: 'nexon' },
		{ name: 'Nike', value: 'nike' },
		{ name: 'Oasis', value: 'oasis' },
		{ name: 'Propel', value: 'propel' },
		{ name: 'Satchi & Satchi', value: 'satchi_satchi' },
		{ name: 'Showtime', value: 'showtime' },
		{ name: 'Skechers', value: 'skechers' },
		{ name: 'Top Rank', value: 'top_rank' },
		{ name: 'Universal Orlando', value: 'universal_orlando' },
		{ name: 'Universal Pictures', value: 'universal_pictures' },
		{ name: 'Universal Studios', value: 'universal_studios' }
	],

	roleClients: [
		{ name: 'Amazon', value: 'amazon' },
		{ name: 'Snap', value: 'snap' },
		{ name: 'Tinder', value: 'tinder' },
		{ name: 'Twitch', value: 'twitch' }
	],

	projectLanguages: [
		{ name: 'ActionScript', value: 'actionscript' },
		{ name: 'C/C++', value: 'c_c_plusplus' },
		{ name: 'CSS', value: 'css' },
		{ name: 'HTML', value: 'html' },
		{ name: 'Javascript', value: 'javascript' },
		{ name: 'PHP', value: 'php' }
	],

	projectResources: [
		{ id: 1, value: 'Adobe After Effects CC' },
		{ id: 2, value: 'Abode AIR' },
		{ id: 3, value: 'Adobe Animate CC' },
		{ id: 4, value: 'Adobe Audition CC' },
		{ id: 5, value: 'Adobe Illustrator CC' },
		{ id: 6, value: 'Adobe InDesign CC' },
		{ id: 7, value: 'Adobe Photoshop CC' },
		{ id: 8, value: 'Adobe Premiere CC' },
		{ id: 9, value: 'Akamai CMS' },
		{ id: 10, value: 'Angular' },
		{ id: 11, value: 'AWS - CodePipeline' },
		{ id: 12, value: 'AWS - Cognito' },
		{ id: 13, value: 'AWS - CloudFront' },
		{ id: 14, value: 'AWS - EC2 Instance' },
		{ id: 15, value: 'AWS - Elastic Beanstalk' },
		{ id: 16, value: 'AWS - Lambda' },
		{ id: 17, value: 'AWS - SES' },
		{ id: 18, value: 'Axios' },
		{ id: 19, value: 'Twitter Bootstrap' },
		{ id: 20, value: 'Box 2D' },
		{ id: 21, value: 'CloudConvert' },
		{ id: 22, value: 'Compass' },
		{ id: 23, value: 'DoubleClick' },
		{ id: 24, value: 'GCS - Maps API' },
		{ id: 25, value: 'Google Web Fonts' },
		{ id: 26, value: 'Grunt' },
		{ id: 27, value: 'Gulp' },
		{ id: 28, value: 'Handlebars' },
		{ id: 29, value: 'Juicer' },
		{ id: 30, value: 'JQuery' },
		{ id: 31, value: 'Laravel' },
		{ id: 32, value: 'Marionette-Backbone' },
		{ id: 33, value: 'Mocha Motion Tracking' },
		{ id: 34, value: 'Modernizr' },
		{ id: 35, value: 'Mustash' },
		{ id: 36, value: 'NodeJS' },
		{ id: 37, value: 'NPM' },
		{ id: 38, value: 'Papervision 3D' },
		{ id: 39, value: 'Particle Illusion' },
		{ id: 40, value: 'PDFjs' },
		{ id: 41, value: 'PointRoll' },
		{ id: 42, value: 'Postman' },
		{ id: 43, value: 'Quill Editor' },
		{ id: 44, value: 'ReactJS' },
		{ id: 45, value: 'REST API' },
		{ id: 46, value: 'SCSS/Sass' },
		{ id: 47, value: 'Service Workers' },
		{ id: 48, value: 'Sizmek/MediaMind' },
		{ id: 49, value: 'SocketJS' },
		{ id: 50, value: 'SquareSpace' },
		{ id: 51, value: 'Stripe' },
		{ id: 52, value: 'ThreeJS' },
		{ id: 53, value: 'Unity Engine' },
		{ id: 54, value: 'Vue Material' },
		{ id: 55, value: 'Vuelidate' },
		{ id: 56, value: 'VueJS' },
		{ id: 57, value: 'Vuetify' },
		{ id: 58, value: 'Vuex' },
		{ id: 59, value: 'Webpack' },
		{ id: 60, value: 'Wordpress' },
		{ id: 61, value: 'Yarn' }
	],

	imageUsageTypes: [
		{ name: 'Thumbnail', value: '' },
		{ name: 'Main', value: '' }
	]
}
