export const VUEX_PROJECTS_FETCH_REQUEST = 'VUEX_PROJECTS_FETCH_REQUEST'
export const VUEX_PROJECTS_FETCH_SUCCESS = 'VUEX_PROJECTS_FETCH_SUCCESS'
export const VUEX_PROJECTS_FETCH_FAILURE = 'VUEX_PROJECTS_FETCH_FAILURE'

export const VUEX_PROJECT_FETCH_REQUEST  = 'VUEX_PROJECT_FETCH_REQUEST'
export const VUEX_PROJECT_FETCH_SUCCESS  = 'VUEX_PROJECT_FETCH_SUCCESS'
export const VUEX_PROJECT_FETCH_FAILURE  = 'VUEX_PROJECT_FETCH_FAILURE'

export const VUEX_PROJECT_CREATE         = 'VUEX_PROJECT_CREATE'
export const VUEX_PROJECT_CREATE_SUCCESS = 'VUEX_PROJECT_CREATE_SUCCESS'
export const VUEX_PROJECT_CREATE_FAILURE = 'VUEX_PROJECT_CREATE_FAILURE'

export const VUEX_PROJECT_TEARDOWN       = 'VUEX_PROJECT_TEARDOWN'